{{- include "ffc-helm-library.container-secret" (list . "ffc-sfi-crown-hosting-prototype.container-secret") -}}
{{- define "ffc-sfi-crown-hosting-prototype.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  {{- end }}
  {{- if .Values.container.relayKeyRule }}
  RELAY_KEY_RULE: {{ quote .Values.container.relayKeyRule }}
  RELAY_KEY: {{ quote .Values.container.relayKey }}
  {{- end }}
{{- end -}}
