{{- include "ffc-helm-library.deployment" (list . "ffc-sfi-crown-hosting-prototype.deployment") -}}
{{- define "ffc-sfi-crown-hosting-prototype.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-sfi-crown-hosting-prototype.container") }}
{{- end -}}
